name: flutter_avif_macos
description: Macos implementation for flutter_avif.
version: 2.0.0
repository: https://github.com/ngsanti/flutter_avif/tree/main/flutter_avif_macos
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface:
    git:
      url: git@github.com:ngsanti/flutter_avif.git
      path: flutter_avif_platform_interface
      ref: main # branch name

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
flutter:
  plugin:
    implements: flutter_avif
    platforms:
      macos:
        pluginClass: FlutterAvifPlugin
        dartPluginClass: FlutterAvifMacos
