name: flutter_avif
description: A flutter plugin to view and encode avif images using libavif.
version: 2.0.0
repository: https://github.com/ngsanti/flutter_avif
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface:
    git:
      url: git@github.com:ngsanti/flutter_avif.git
      path: flutter_avif_platform_interface
      ref: main # branch name
  flutter_avif_android:
    git:
      url: git@github.com:ngsanti/flutter_avif.git
      path: flutter_avif_android
      ref: main # branch name
  flutter_avif_ios:
    git:
      url: git@github.com:ngsanti/flutter_avif.git
      path: flutter_avif_ios
      ref: main # branch name
  flutter_avif_macos:
    git:
      url: git@github.com:ngsanti/flutter_avif.git
      path: flutter_avif_macos
      ref: main # branch name
  flutter_avif_linux:
    git:
      url: git@github.com:ngsanti/flutter_avif.git
      path: flutter_avif_linux
      ref: main # branch name
  flutter_avif_windows:
    git:
      url: git@github.com:ngsanti/flutter_avif.git
      path: flutter_avif_windows
      ref: main # branch name
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  
flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_avif_android
      ios:
        default_package: flutter_avif_ios
      macos:
        default_package: flutter_avif_macos
      linux:
        default_package: flutter_avif_linux
      windows:
        default_package: flutter_avif_windows
